Minor Changes
RareSkills/zk-book pull request #35
Opened 2024-10-26 12:09 UTC by RDxR10

Format correction, grammar fix

2024-10-27 04:52 UTC, RareSkills commented on content/homomorphisms/en/homomorphisms.md
> +b^{a_i + a_j}=\underbrace{b\cdot b\cdot\dots\cdot b}_{{a_i} \text{ times}} \cdot \underbrace{b \cdot b \cdot \dots \cdot b} _{a_j \text{ times}}
can we undo the changes in this file? It's not clear how this changes the formula rendering.

2024-10-27 04:52 UTC, RareSkills requested changes
please see comment in homomorphisms.md, it's probably best to revert the changes there.

python-lagrange-interpolation.py is good, thanks!

2024-10-27 04:52 UTC, RareSkills commented on content/homomorphisms/en/homomorphisms.md
> -The good news is, we are done with our treatment of abstract algebra, and we now have a strong foundation to move on to [elliptic curves](https://www.rareskills.io/post/elliptic-curve-addition).
same here

2024-10-27 06:55 UTC, RareSkills commented
@RDxR10 can you explain the latex changes in homomorphisms.md?

It isn't clear that this changes the formula rendering and seems to be creating an unnecessary diff.

2024-10-27 07:39 UTC, RDxR10 commented
TBH I'm not sure either. But I'm guessing that the parser is unable to interpret what's markdown and what's LATEX.

For the other one: `elliptic-curves-finite-fields.md`
1. `has_sqrtmod_prime_power` was imported twice.
2. `libnum` was used without directly without importing (which is not required).

2024-11-17 10:02 UTC, RareSkills approved these changes

2024-11-17 10:02 UTC, merged