Patch ZK Multiplication Post
RareSkills/zk-book pull request #37
Opened 2024-10-27 14:32 UTC by marcobesier

Minor improvements

2024-10-28 13:30 UTC, RareSkills commented on content/zk-multiplication/en/zk-multiplication.md
> +The verifier checks that each of the polynomials were evaluated correctly and that the evaluation of $t(u)$ is the product of the evaluation of $l(u)$ and $r(u)$. The first three checks are proofs th
we should say "the last check verifies that"

"proof" is a piece of data supplied by the verifier, not an equation satisfaction

2024-10-28 13:31 UTC, RareSkills requested changes
small change request, rest is good

2024-10-28 13:40 UTC, marcobesier commented
Done 🤝

2024-10-29 03:26 UTC, RareSkills approved these changes

2024-10-29 03:27 UTC, merged